name: common_dependency_module
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.31.0
  cloud_firestore: 4.17.3
  flutter_modular: 6.3.3
  flutter_svg: 2.0.10
  equatable: 2.0.5
  flutter_bloc: 8.1.5
  logger: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

