// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:common_dependency_module/common_dependency_module.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsM6UxNRCtHmfTovM402qWKD1RT5o7He4',
    appId: '1:496528477808:ios:2eef241a40fca9b2f3aeb5',
    messagingSenderId: '496528477808',
    projectId: 'mi-proyecto-18c31',
    databaseURL: 'https://mi-proyecto-18c31.firebaseio.com',
    storageBucket: 'mi-proyecto-18c31.firebasestorage.app',
    iosBundleId: 'com.example.taskAppTechTest',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzdu6LWOA8b-wiooshtHGCsweZ-ive7kg',
    appId: '1:496528477808:android:bbd8f98a66f5b868f3aeb5',
    messagingSenderId: '496528477808',
    projectId: 'mi-proyecto-18c31',
    databaseURL: 'https://mi-proyecto-18c31.firebaseio.com',
    storageBucket: 'mi-proyecto-18c31.firebasestorage.app',
  );
}
